### ISSUE TITLE
Notify value changes

### ISSUE THREAD

**Issue by rooi** [etwmc/Personal-HomeKit-HAP-#19]
Hi,

I just saw in your ready that you would like to include notifications. I just tried the ask siri to notify when my lights turn on and it actually tried to do it. Unfortunatly it did not work, but it seems it's possible. Is this correct?
If so, do you still plan to include notifications and when? Perhaps I can assist in some way if you give me some pointers on how to achieve this.
Either way thanks you very much!

Roy

**Comment by etwmc** [comment]
rooi: Do you still have the malloc problems? I don't really have time to fully test the new pulls these few months, but I would like to know if there's still problems.

**Comment by rooi** [comment]
@etwmc I did not see the error since I started using my mac mini instead of my raspberry.
I think this issue can be closed.

Thanks!
