### ISSUE TITLE
C# port data request

### ISSUE THREAD

**Issue by wzoet** [etwmc/Personal-HomeKit-HAP-#26]
Hi,

I am making a port to c#.
Because the absence of right functioning libraries I had to create some myself already (chacha20poly1305 and specific SRP implementation).

At this moment I am stuck on verifying the controller info signature using Ed25519.
Could you give me some intermediate values of your project in hex-byte arrays? Eg the shared secret, the session key, input and output of chacha20poly1305 algorithm and preferably the deserialized tlv data of that? The other inputs for the ed25519 algorithm as well of course. 

That way I could check my source to see where it fails. I assume it is the ed25519 library I am using this time or some byte gets lost during an earlier process.
Since I get to m5 the session key and therefore shared secret must be right. 
I can also deserialize tlv data after decrypting chachapoly so those algorithms work as well. I just can't verify the signature in the decrypted subtlv data.

Thank you very much!

**Comment by Clancey** [comment]
@Wzoet did you get very far? This is something I am about to start on.

**Comment by wzoet** [comment]
I do have a working version of the code now. Unfortunately still sometimes my ChachaPoly1305 algorithm failes to verify the tag on encrypted data.

**Comment by Clancey** [comment]
Would you mind putting it up on github?  I would love to help contribute.

**Comment by wzoet** [comment]
Sorry to say but I am not allowed to because of NDA. Shortly after posting I was granted access to the MFi program which is strictly regulated.
Even with the correct manuals this is tough matter to handle, let alone without...
