### ISSUE TITLE
fan and light Accessory.cpp

### ISSUE THREAD

**Issue by gb160** [etwmc/Personal-HomeKit-HAP-#42]
Hi, I'm trying to use the fan and light Accessory.cpp but I'm getting error with make....

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jun  9 19:06:36 2015 from gavsmac
pi@Raspbian ~ $ cd Personal-HomeKit-HAP-
pi@Raspbian ~/Personal-HomeKit-HAP- $ sudo make
gcc -O0 -w -o chacha20.o -c Chacha20/chacha20_simple.c
gcc -O0 -w -o curve25519.o -c curve25519/curve25519-donna.c
gcc -O0 -w -o ed25519.o -c ed25519-donna/ed25519.c
gcc -O0 -w -o poly1305.o -c poly1305-opt-master/poly1305.c
gcc -O0 -w -c rfc6234-master/hkdf.c -o rfc6234-master/hkdf.o
gcc -O0 -w -c rfc6234-master/hmac.c -o rfc6234-master/hmac.o
gcc -O0 -w -c rfc6234-master/sha.c -o rfc6234-master/sha.o
g++ -O0 -w -c main.cpp
g++ -O0 -w -c PHKAccessory.cpp
g++ -O0 -w -c PHKControllerRecord.cpp
g++ -O0 -w -c PHKNetworkIP.cpp
gcc    -c -o PHKArduinoLightInterface.o PHKArduinoLightInterface.c
gcc -O0 -lcrypto -w -c srp/srp.c -o srp/srp.o
gcc -O0 -lcrypto -w -c srp/cstr.c -o srp/cstr.o
gcc -O0 -lcrypto -w -c srp/t_math.c -o srp/t_math.o
gcc -O0 -lcrypto -w -c srp/srp6_server.c -o srp/srp6_server.o
gcc -O0 -lcrypto -w -c srp/t_conf.c -o srp/t_conf.o
gcc -O0 -lcrypto -w -c srp/t_conv.c -o srp/t_conv.o
gcc -O0 -lcrypto -w -c srp/t_pw.c -o srp/t_pw.o
gcc -O0 -lcrypto -w -c srp/t_misc.c -o srp/t_misc.o
gcc -O0 -lcrypto -w -c srp/t_truerand.c -o srp/t_truerand.o
gcc -O0 -lcrypto -w -c srp/t_read.c -o srp/t_read.o
g++ -O0 -w -c Accessory.cpp
Accessory.cpp: In function ‘void initAccessorySet()’:
Accessory.cpp:22:77: error: too few arguments to function ‘void addInfoServiceToAccessory(Accessory*, std::string, std::string, std::string, std::string, identifyFunction)’
     addInfoServiceToAccessory(lightAcc, "Light 1", "ET", "Light", "12345678");
                                                                             ^
In file included from Accessory.cpp:7:0:
PHKAccessory.h:321:6: note: declared here
 void addInfoServiceToAccessory(Accessory *acc, string accName, string manufactuerName, string modelName, string serialNumber, identifyFunction identifyCallback);
      ^
Accessory.cpp:42:68: error: too few arguments to function ‘void addInfoServiceToAccessory(Accessory*, std::string, std::string, std::string, std::string, identifyFunction)’
     addInfoServiceToAccessory(fan, "Fan 1", "ET", "Fan", "12345678");
                                                                    ^
In file included from Accessory.cpp:7:0:
PHKAccessory.h:321:6: note: declared here
 void addInfoServiceToAccessory(Accessory *acc, string accName, string manufactuerName, string modelName, string serialNumber, identifyFunction identifyCallback);
      ^
makefile:36: recipe for target 'Accessory.o' failed
make: *** [Accessory.o] Error 1
pi@Raspbian ~/Personal-HomeKit-HAP- $

**Comment by gb160** [comment]
I can make with the default Accessory.cpp and that works ok....am i doing something wrong?

**Comment by gb160** [comment]
Any news on this issue ?
Do u know what the last version that works with fan and light together is ?
Regards

**Comment by gb160** [comment]
Can u verify that multiple devices are not supported anymore? 
I'll try a different project if so.

**Comment by etwmc** [comment]
For some reason github didn't send any issues of this repo to my email anymore. So sorry if it takes so long to reply. 
The code is still support multiple accessories (the bridge mode). It's just a small changes from the single accessory structure, by adding more accessories in the process. 
For the failure of the example, I might change too many function arguments during the update for iOS 8.3 and iOS 9.0 beta 1. I will rewrite it in the morning.

**Comment by gb160** [comment]
ok mate, understood.

**Comment by etwmc** [comment]
The code has fixed. (it's actually add an identify function)
