### ISSUE TITLE
fan and light Accessory.cpp

### ISSUE THREAD

**Issue by gb160** [etwmc/Personal-HomeKit-HAP-#43]
Im still getting errors with make...I haven't modified the fan+light.cpp at all, except renaming it.

pi@Raspbian ~/Personal-HomeKit-HAP- $ sudo make all
gcc -O0 -w -o chacha20.o -c Chacha20/chacha20_simple.c
gcc -O0 -w -o curve25519.o -c curve25519/curve25519-donna.c
gcc -O0 -w -o ed25519.o -c ed25519-donna/ed25519.c
gcc -O0 -w -o poly1305.o -c poly1305-opt-master/poly1305.c
gcc -O0 -w -c rfc6234-master/hkdf.c -o rfc6234-master/hkdf.o
gcc -O0 -w -c rfc6234-master/hmac.c -o rfc6234-master/hmac.o
gcc -O0 -w -c rfc6234-master/sha.c -o rfc6234-master/sha.o
g++ -O0 -w -c main.cpp
g++ -O0 -w -c PHKAccessory.cpp
g++ -O0 -w -c PHKControllerRecord.cpp
g++ -O0 -w -c PHKNetworkIP.cpp
gcc    -c -o PHKArduinoLightInterface.o PHKArduinoLightInterface.c
gcc -O0 -lcrypto -w -c srp/srp.c -o srp/srp.o
gcc -O0 -lcrypto -w -c srp/cstr.c -o srp/cstr.o
gcc -O0 -lcrypto -w -c srp/t_math.c -o srp/t_math.o
gcc -O0 -lcrypto -w -c srp/srp6_server.c -o srp/srp6_server.o
gcc -O0 -lcrypto -w -c srp/t_conf.c -o srp/t_conf.o
gcc -O0 -lcrypto -w -c srp/t_conv.c -o srp/t_conv.o
gcc -O0 -lcrypto -w -c srp/t_pw.c -o srp/t_pw.o
gcc -O0 -lcrypto -w -c srp/t_misc.c -o srp/t_misc.o
gcc -O0 -lcrypto -w -c srp/t_truerand.c -o srp/t_truerand.o
gcc -O0 -lcrypto -w -c srp/t_read.c -o srp/t_read.o
g++ -O0 -w -c Accessory.cpp
In file included from Accessory.cpp:7:0:
PHKAccessory.h: In function ‘void initAccessorySet()’:
PHKAccessory.h:297:5: error: ‘AccessorySet::AccessorySet()’ is private
     AccessorySet() {
     ^
Accessory.cpp:21:31: error: within this context
     accSet = new AccessorySet();
                               ^
Accessory.cpp:23:80: error: ‘lightIdentify’ was not declared in this scope
     addInfoServiceToAccessory(lightAcc, "Light 1", "ET", "Light", "12345678", &lightIdentify);
                                                                                ^
Accessory.cpp:43:71: error: ‘fanIdentify’ was not declared in this scope
     addInfoServiceToAccessory(fan, "Fan 1", "ET", "Fan", "12345678", &fanIdentify);
                                                                       ^
makefile:42: recipe for target 'Accessory.o' failed
make: *** [Accessory.o] Error 1
pi@Raspbian ~/Personal-HomeKit-HAP- $

**Comment by etwmc** [comment]
Sorry. Forget to copy a few line while updating on the browser. 
It should be fixed by now. 

If not, I will just speed up the next commit for iOS 9. (Most of my codes are now include the new types from iOS 9, so it's not really compatible to the current commit. )

**Comment by gb160** [comment]
No problem, can confirm its working great now !
